### ISSUE TITLE
Documentation: Resolving Apache Configuration Conflict Causing HTTPD Service Failure

### ISSUE THREAD

**Issue by krishmoodbidri** [eesaanatluri/CRI_Cluster_Monitor#7]
When multiple Apache configuration files are present on a server, they can sometimes conflict with each other and cause issues with the HTTPD service. One common issue is when two configuration files rewrite traffic to port 443, causing the HTTPD service to fail. This documentation will provide steps to resolve this issue.

Step 1: Identify the conflicting configuration files
The first step is to identify the two Apache configuration files that are causing the conflict. In this case, we know that ssl.conf and xdmod.conf are conflicting. It is essential to understand which configuration file is being applied first to determine the root cause of the problem.

Step 2: Temporarily disable one of the conflicting configuration files
To resolve the conflict, we will temporarily disable one of the conflicting configuration files. In this case, we will disable ssl.conf by renaming it to ssl.conf.abc. To do this, execute the following command:

sudo mv /etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ssl.conf.abc

This command renames the ssl.conf file to ssl.conf.abc, which effectively disables it.

Step 3: Restart the HTTPD service
After disabling one of the conflicting configuration files, we need to restart the HTTPD service to apply the changes. Execute the following command to restart the HTTPD service:

sudo systemctl restart httpd.service

This command will restart the HTTPD service, and the server should now be accessible over HTTP.

Step 4: Verify the fix
After restarting the HTTPD service, we need to verify that the fix has resolved the issue. Access the server over HTTP and ensure that it is accessible. Then, check the Apache error logs to ensure that there are no errors related to the conflicting configuration files.

**Comment by eesaanatluri** [comment]
so xdmod.conf is the default apache config but when ssl.conf is present it takes precedence over default xdmod.conf . There is already a line in ssl.conf Listen 443 https so that is in conflict with the Listen 443 line in xdmod.conf.

I think the solution would be to remove the line `Listen 443` from the apache config xdmod.conf and let default ssl.conf handle it instead of moving the default files provided by CenOS 7 around.
